### ISSUE TITLE
Make user friendly GUI with Tkinter or PyQt5

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#16]

**Comment by lvps** [comment]
@e-caste Possibly PyQt5, it's much more user friendly. For users, at least. Not really for programmers. asd

**Comment by lvps** [comment]
I was thinking: a small GUI for the "Is the GPU integrated or dedicated?" questions is a good idea, as it is for asking users "Find the model in these 2 lines of text and copy it" when regexes just don't cut it.

However, if the idea was to make something more complex, that allows editing every single feature, that's probably too much, and let me explain why.

When we planned this project, we thought it should be a small script that gathers data in a quick and dirty manner and uploads everything to the tarallo. At the time, tarallo was also more rudimentary: when you add an item, you add to insert every feature manually (instead of selecting type and getting the most common features), no "copy" function, possibly not even the "history" page. So scraping some data and shoving it into the APIs (those already existed and didn't change much from those times) seemed a good idea.

However, the "copy" function is a demonstration that it is very easy to add a new item based on an existing one. I mean, even if you don't understand PHP, the code is literally these 7 lines inside the "add a new item" method:

```php
$from = Validation::validateOptionalString($query, 'copy', null);

if($from !== null) {
	/** @var Database $db */
	$db = $request->getAttribute('Database');
	$from = $db->itemDAO()->getItem(new ItemIncomplete($from));
}
```

Moreover, I've recently worked on better handling of empty features in edit mode, which means that we can add to that a list of "default" features, like the ones that you get when when selecting a type in the "add a new item" page. This may need some more coding, but having an item with some features already filled and adding some others to be filled manually, from a list of default features, should be very easy. Do you see where I'm going with this?

We now have three choices, after all data has been read:

1. Create the items in the tarallo via pytarallo and add a special flag like "manual revision is needed". Then someone will open the items on tarallo and add all the missing features.
2. Export a json file, which can be uploaded to the tarallo and it will show the "add a new item" page filled with all possible input, since now we know how to upload files thanks to @Quadrollopo asd
3. An intermediate solution: upload the JSON via a new API and store it as-is in the database, then read it later to show the "add a new item" page (the difference is that items are added and receive a code upon manual revision, not instantly)

1 is the epitome of automation and very cool.  
However, 2 is probably simpler (no pytarallo to integrate here, no modification to the APIs, just templates) and less error prone (what if you forget to do the manual revision?).  
3 is cool like 1 but simpler to implement and can be built upon 2.

Also, for the "Find the model in these two lines of text" and similar things, we could think of a way to show them in the tarallo right above the feature, to simplify even more the peracotta GUI. In this case, choices 2 and 3 are probably waaaaay simpler since they leave us complete freedom on the structure of the exported JSON, while 1 would require significant changes to the API and database schema and and the JSON should match them.
