### ISSUE TITLE
Fix Serial (DE-9) is often found

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#42]
Even when it's not in the mobo

**Comment by lvps** [comment]
As discussed in person, this is probably due to internal serial headers and
it may not be convenient to fix them.

Port information is correct on some motherboards and completely wrong in
every respect on others, trying to correct them automatically may not be
worth it


Il gio 19 dic 2019, 18:40 e-caste <notifications@github.com> ha scritto:

**Comment by e-caste** [comment]
Added wontfix label due to @lvps 's comment, closing.
