### ISSUE TITLE
Make normalized manufacturers names text file

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/peracotta#60]
This will also be used in the Tarallo Inventory System ™️ to avoid having multiple names for a single manufacturer. An example would be Asus that may be called AsusTek, ASUS, Asus Inc., AsusTek Inc. etc. 

The input are the attached text file, which is a dump of the current Tarallo items' manufacturers, and the content of the `test/` directory of this repository.  
[brands.txt](https://github.com/WEEE-Open/peracotta/files/5404904/brands.1.txt)
The expected output is a Python `dict` saved as a JSON file which contains as keys the many non-normalized names of brands and as values the normalized name (one for each key). This is space-inefficient but compute-efficient, since we can then just load the JSON as a `dict` and search the normalized name by key.

To do this, you can write a script that tries to parse similar strings, or look brands up on the Internet, or both.
The normalized names should be Capitalized but not in CAPS LOCK.

This issue has to be done before #56

**Comment by lvps** [comment]
By the way, the list is non-exclusive: if a brand doesn't appear there, use it as-is, we cannot possibly have a list of all existing brands.

A consequence is that you can avoid normalizing the normalized names.

e.g. we have a csv file with the "wrong" name column and the normalized name, like this:

```csv
AsusTek,ASUS
Asus Inc.,ASUS
AsusTek Computer,ASUS
AsusTek Inc.,ASUS
```
We don't need ASUS,ASUS, since that's already the normalized form.
But what if peracotta detects Asus, and the normalized form is ASUS? This is left as an exercise to the reader, i.e. find a solution to also have the correct case (which could involve adding the `ASUS,ASUS` line, if you think it's the best way)

The list is just an example of the normalized names that we expect, although some are not normalized (`TPV ELECTRONICS(FUJIAN)` should be `TPV Technology`, that's apparently the most well-known name for that company which I knew nothing about) or some are wrong (`S3` is wrong, it should be `S3+`... probably)

**Bonus points**: partial matching and suggesting similar normalized names in the GUI asd

**Comment by lvps** [comment]
By the way, the same list will be reused in the tarallo (https://github.com/WEEE-Open/tarallo/issues/69). For now just make a csv, in the future we may provide it from an API.

**Comment by e-caste** [comment]
After our meeting, we have found that we need:  
- the script to generate the file
- the generated .csv file 
- a function to parse the csv file into a Python dictionary
